name: run collector.py

on:
  schedule:
    - cron: '*/5 10-20 * 3-11 *'
    
jobs:
  build:
    runs-on: ubunto-latest
    steps:

    - name: Checkout Repository Content
      uses: actions/checkout@v2

    - name: Settup Python
      uses: actions/settup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python Packages
      run:
        python -m pip install --upgrade pip
        pip intall -r requirements.txt

    - name: Execute the Python Script
      run: python queueTimesCollector.py

    - name: Commit Files
      run: |
        git config --local user.email "action@github.com"
        git config --logal user.name "Github Action"
        git add -A
        git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

    - name: Push Changes
      uses: ad-m/github-push-action@v0.6.0
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
